# Development override for docker-compose
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Use builder stage for development
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      DEBUG: "true"
      LOG_LEVEL: DEBUG
    volumes:
      # Mount source code for hot reload
      - ./app:/app/app:delegated
      - ./tests:/app/tests:delegated
      - ./alembic:/app/alembic:delegated
    ports:
      - "8000:8000"
      - "5678:5678"  # debugpy port

  db:
    ports:
      - "5432:5432"
    # Expose PostgreSQL for direct access during development

  redis:
    ports:
      - "6379:6379"
    # Expose Redis for direct access during development
