services:
  # PostgreSQL database with pgvector extension
  db:
    image: ankane/pgvector:latest
    container_name: synapse-db
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: synapse
      POSTGRES_INITDB_ARGS: "-E UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapse -d synapse"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - synapse-network

  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: synapse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - synapse-network

  # FastAPI application
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: synapse-api
    environment:
      # Application
      ENVIRONMENT: development
      DEBUG: "true"

      # Database
      DATABASE_URL: postgresql://synapse:synapse@db:5432/synapse

      # Redis
      REDIS_URL: redis://redis:6379/0

      # JWT
      JWT_SECRET_KEY: dev-secret-key-change-in-production

      # AI Models
      EMBEDDING_MODEL: intfloat/multilingual-e5-large
      EMBEDDING_DEVICE: cpu
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - model_cache:/home/synapse/.cache
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - synapse-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  model_cache:
    driver: local

networks:
  synapse-network:
    driver: bridge
